### ISSUE TITLE
Crash while loading mine craft 1.9

### ISSUE THREAD

**Issue by dextermovies** [GoryMoon/MoarSigns#19]
Here is the Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.9.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  CXLibraryCore (cxlibrary-1.0.0.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/20/16 4:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
	at invtweaks.InvTweaksItemTree.lambda$oreRegistered$5(InvTweaksItemTree.java:288)
	at invtweaks.InvTweaksItemTree$$Lambda$14/344496616.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at invtweaks.InvTweaksItemTree.oreRegistered(InvTweaksItemTree.java:288)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_132_InvTweaksItemTree_oreRegistered_OreRegisterEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:522)
	at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:469)
	at gory_moon.moarsigns.items.ModItems.registerRecipes(ModItems.java:110)
	at gory_moon.moarsigns.MoarSigns.modsLoaded(MoarSigns.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 445558376 bytes (424 MB) / 4153815040 bytes (3961 MB) up to 8160477184 bytes (7782 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJ	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJ	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHIJ	abyssalcraft{1.9.1-pre-1} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1-pre-1.jar) 
	UCHIJ	Baubles{1.2.0.0} [Baubles] (Baubles-1.9-1.2.0.0.jar) 
	UCHIJ	BiomesOPlenty{4.0.2.2012} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2012-universal.jar) 
	UCHIJ	BloodMagic{1.9-2.0.0-33} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-33.jar) 
	UCHIJ	samsbucketblocks{1.0.1} [Bucket Storage] (BucketBlocks-1.9-1.0.1.jar) 
	UCHIJ	buildingbrickscompatvanilla{1.9-1.4.8} [Building Bricks Vanilla Compat] (BuildingBricks-1.9-1.4.8.jar) 
	UCHIJ	buildingbricks{1.9-1.4.8} [Building Bricks] (BuildingBricks-1.9-1.4.8.jar) 
	UCHIJ	craftablehorsearmour{1.0} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmourAndSaddle-1.0.jar) 
	UCHIJ	craftingcraft{3.0.3} [CraftingCraft] (craftingcraft-mc1.9-3.0.3.jar) 
	UCHIJ	cxlibrary{1.0.0} [CXLibrary] (cxlibrary-1.0.0.jar) 
	UCHIJ	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJ	substratum{1.3.0.0} [Substratum] (Substratum-1.9-1.3.0.0.jar) 
	UCHIJ	foundry{2.0.0.0-alpha1} [Foundry] (Foundry-1.9-2.0.0.0-alpha1.jar) 
	UCHIJ	hgp{Release} [Horizontal Glass Panes] (hgp-1.9-1.0.2.jar) 
	UCHIJ	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJ	inventorytweaks{1.61-dev-44-8aeffff} [Inventory Tweaks] (InventoryTweaks-1.61-dev-44.jar) 
	UCHIJ	IronChest{6.0.126.771} [Iron Chest] (ironchest-1.9-6.0.126.771.jar) 
	UCHIJ	lteleporters{1.1.1} [Lemon's Simple Teleporters] (LemonsSimpleTeleporters-1.1.1.jar) 
	UCHIJ	lucky{7.1.1} [Lucky Block] (LuckyBlock_1-9_v7-1-1.zip) 
	UCHIJ	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJ	more{7.0 beta 2} [M-Ore mod] (M-Ore 7.2 1.9.jar) 
	UCHIJ	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIE	moarsigns{3.0.0} [MoarSigns] (MoarSigns-1.9-3.0.0.jar) 
	UCHIJ	MoreFurnaces{1.6.0} [More Furnaces] (MoreFurnaces-1.6.0-MC1.9.jar) 
	UCHIJ	morematerials{1.0.20150301.0} [More Materials] (morematerials-1.9.20160320.0.jar) 
	UCHIJ	Morpheus{1.9-3.0.1} [Morpheus] (Morpheus-1.9-3.0.1.jar) 
	UCHIJ	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.9.jar) 
	UCHIJ	fodc{1.8.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.0.jar) 
	UCHIJ	packingtape{0.5.1} [Packing Tape] (Packing Tape-0.5.1.jar) 
	UCHIJ	parachutemod{1.4.1} [Parachute Mod] (parachutemod-ng-1.9-1.4.1-395.jar) 
	UCHIJ	planttech{1.4.0} [Planttech] (planttech-1.4.0 - 1.9.jar) 
	UCHIJ	progressiveautomation{1.6.41} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.41.jar) 
	UCHIJ	RealisticTorches{1.5.3} [Realistic Torches] (RealisticTorches-1.9-1.5.3.jar) 
	UCHIJ	reinforcedTools{1.4.1} [ReinforcedTools] (ReinforcedTools-1.4.1 for MC1.9.jar) 
	UCHIJ	rftools{4.30} [RFTools] (rftools-1.9.0-4.30.jar) 
	UCHIJ	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.1.jar) 
	UCHIJ	supercraftingframe{1.1.0.38} [Super Crafting Frame] (supercraftingframe-1.9-1.1.0.38.jar) 
	UCHIJ	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJ	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.2-mf-1.9-12.16.0.1811.jar) 
	UCHIJ	XaeroMinimap{1.8.7} [Xaero's Minimap] (Xaeros_Minimap_1.8.7_Forge_1.9.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.9.jar)
  com.creativemd.itemphysic.ItemTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CXLibraryCore (cxlibrary-1.0.0.jar)
  cubex2.cxlibrary.CoreModTransformer
FMLPlugin (InventoryTweaks-1.61-dev-44.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon 3000 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)ssor

**Comment by GoryMoon** [comment]
Nothing to do with me, error lies at Inventory Tweaks.
To have the current version of Inventory Tweaks working you need use Forge version 12.16.0.1804 or below, or have a version of Inventory Tweaks compiled for versions above that.

The error lies here: 
https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/InvTweaksItemTree.java#L288
combined with these changes:
https://github.com/MinecraftForge/MinecraftForge/commit/756c58d5cb01ed33e9bbc165ab62cc62244d6bb1#diff-b5ca2d4294ff8ffd8269999435da187eL524
