### ISSUE TITLE
Client crash when using the toolbox on a sign

### ISSUE THREAD

**Issue by SubsterNL** [GoryMoon/MoarSigns#30]
1.10.2
Forge 2151 (but presumably also on previous versions).
Unstable type like modpack through multimc but all mods updated

**Comment by GoryMoon** [comment]
Need log of it happening, can't reproduce myself.

**Comment by SubsterNL** [comment]
Not sure if this enough of what you need but it still happens with forge updated and such.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (sampler-1.66.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.5r.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 12/7/16 9:04 AM
Description: Unexpected error

java.lang.NoSuchMethodError: cofh.api.item.IToolHammer.isUsable(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;III)Z
	at gory_moon.moarsigns.blocks.BlockMoarSign.func_180639_a(BlockMoarSign.java:125)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
--------`

**Comment by GoryMoon** [comment]
Ok, I've just been quite busy later
