### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by mezz** [GoryMoon/MoarSigns#32]
Hello,

There is a small problem in your JEI integration:
The `MoarSignsRecipeWrapper` must implement `ICraftingRecipeWrapper` in order to be accepted into the crafting recipe category.

Players get this crash when looking up the recipe for the Actually Additions crafting table on a stick. Since it uses a sign in the recipe, it gets replaced with your recipe type.

```
[05:31:26] [Client thread/ERROR] [JEI]: Error caught from Recipe Category: mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory
java.lang.ClassCastException: gory_moon.moarsigns.integration.jei.crafting.MoarSignsRecipeWrapper cannot be cast to mezz.jei.api.recipe.wrapper.ICraftingRecipeWrapper
	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.setRecipe(CraftingRecipeCategory.java:20) ~[CraftingRecipeCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.<init>(RecipeLayout.java:78) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:217) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:433) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73866_w_(RecipesGui.java:156) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:495) [bft.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965) [bcx.class:?]
	at mezz.jei.gui.recipes.RecipesGui.open(RecipesGui.java:316) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:339) [RecipesGui.class:?]
	at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:147) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:83) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:60) [InputHandler.class:?]
	at mezz.jei.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:140) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1249_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:516) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

In the latest JEI I have suppressed the crash, but it will show a blank recipe until this issue is fixed.

**Comment by mezz** [comment]
Actually now that I look at it, there is really no need for the `ICraftingRecipeWrapper` any more in 1.10 and higher so I will phase it out. I don't think you will need to change anything. I'll close this issue once I finish the implementation.

**Comment by mezz** [comment]
Fixed on JEI's side, `ICraftingRecipeWrapper` is no longer needed.

**Comment by GoryMoon** [comment]
It is fixed in an newer version of MoarSigns, Sky Factory 3 hasn't been updated with it yet tough, you can see the change here: https://github.com/GoryMoon/MoarSigns/commit/faebd1ccda17a97898bf43e11d9cd953bed665e4#diff-bc40acd83ad7b9b022e9dbf19e26f11dR18
